import { Router, type IRouter } from "express";
import healthRouter from "./health/health";
import teachersRouter from "./teachers/teachers";
import studentsRouter from "./students/students";
import sessionsRouter from "./sessions/sessions";
import authRouter from "./auth/auth";
import invitationsRouter from "./auth/invitations";
import billingRouter from "./billing/billing";
import storageRouter from "./storage/storage";
import contactRouter from "./contact/contact";
import speechRouter from "./speech/speech";
import districtsRouter from "./districts/districts";
import districtPlanRouter from "./districts/district-plan";
import schoolsRouter from "./schools/schools";
import adminRouter from "./admin/admin";
import agentRouter from "./agent/agent";
import mediaRouter from "./media/media";
import imageScansRouter from "./image-scans/image-scans";
import imagesRouter from "./images/images";
import detectRouter           from "./images/detect";
import generateQuestionRouter from "./images/generate-question";
import scanRouter             from "./images/scan";

const router: IRouter = Router();

router.use(imagesRouter);
router.use(detectRouter);
router.use(generateQuestionRouter);
router.use(scanRouter);
router.use(agentRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(invitationsRouter);
router.use(teachersRouter);
router.use(studentsRouter);
router.use(sessionsRouter);
router.use(billingRouter);
router.use(storageRouter);
router.use(contactRouter);
router.use(speechRouter);
router.use(districtsRouter);
router.use(districtPlanRouter);
router.use(schoolsRouter);
router.use(adminRouter);
router.use(mediaRouter);
router.use(imageScansRouter);

export default router;
